// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VECTORRECORDS_H_
#define FLATBUFFERS_GENERATED_VECTORRECORDS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

struct VectorRecord;
struct VectorRecordBuilder;

struct VectorRecords;
struct VectorRecordsBuilder;

struct VectorRecord FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorRecordBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VECTOR = 4,
    VT_NORM = 6,
    VT_PERSON_NAME = 8
  };
  const ::flatbuffers::Vector<float> *vector() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VECTOR);
  }
  float norm() const {
    return GetField<float>(VT_NORM, 0.0f);
  }
  const ::flatbuffers::String *person_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PERSON_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VECTOR) &&
           verifier.VerifyVector(vector()) &&
           VerifyField<float>(verifier, VT_NORM, 4) &&
           VerifyOffset(verifier, VT_PERSON_NAME) &&
           verifier.VerifyString(person_name()) &&
           verifier.EndTable();
  }
};

struct VectorRecordBuilder {
  typedef VectorRecord Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vector(::flatbuffers::Offset<::flatbuffers::Vector<float>> vector) {
    fbb_.AddOffset(VectorRecord::VT_VECTOR, vector);
  }
  void add_norm(float norm) {
    fbb_.AddElement<float>(VectorRecord::VT_NORM, norm, 0.0f);
  }
  void add_person_name(::flatbuffers::Offset<::flatbuffers::String> person_name) {
    fbb_.AddOffset(VectorRecord::VT_PERSON_NAME, person_name);
  }
  explicit VectorRecordBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectorRecord> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectorRecord>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VectorRecord> CreateVectorRecord(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> vector = 0,
    float norm = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> person_name = 0) {
  VectorRecordBuilder builder_(_fbb);
  builder_.add_person_name(person_name);
  builder_.add_norm(norm);
  builder_.add_vector(vector);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VectorRecord> CreateVectorRecordDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *vector = nullptr,
    float norm = 0.0f,
    const char *person_name = nullptr) {
  auto vector__ = vector ? _fbb.CreateVector<float>(*vector) : 0;
  auto person_name__ = person_name ? _fbb.CreateString(person_name) : 0;
  return CreateVectorRecord(
      _fbb,
      vector__,
      norm,
      person_name__);
}

struct VectorRecords FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorRecordsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORDS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<VectorRecord>> *records() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<VectorRecord>> *>(VT_RECORDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RECORDS) &&
           verifier.VerifyVector(records()) &&
           verifier.VerifyVectorOfTables(records()) &&
           verifier.EndTable();
  }
};

struct VectorRecordsBuilder {
  typedef VectorRecords Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_records(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VectorRecord>>> records) {
    fbb_.AddOffset(VectorRecords::VT_RECORDS, records);
  }
  explicit VectorRecordsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectorRecords> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectorRecords>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VectorRecords> CreateVectorRecords(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<VectorRecord>>> records = 0) {
  VectorRecordsBuilder builder_(_fbb);
  builder_.add_records(records);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VectorRecords> CreateVectorRecordsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<VectorRecord>> *records = nullptr) {
  auto records__ = records ? _fbb.CreateVector<::flatbuffers::Offset<VectorRecord>>(*records) : 0;
  return CreateVectorRecords(
      _fbb,
      records__);
}

inline const VectorRecords *GetVectorRecords(const void *buf) {
  return ::flatbuffers::GetRoot<VectorRecords>(buf);
}

inline const VectorRecords *GetSizePrefixedVectorRecords(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<VectorRecords>(buf);
}

inline bool VerifyVectorRecordsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<VectorRecords>(nullptr);
}

inline bool VerifySizePrefixedVectorRecordsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<VectorRecords>(nullptr);
}

inline void FinishVectorRecordsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VectorRecords> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVectorRecordsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<VectorRecords> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_VECTORRECORDS_H_
